"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/lib/auth-context";
import { competitors, ai, intel, type CompetitorAnalysis, type IntelFeed } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/empty-state";
import { Shield, Sparkles, Loader2 } from "lucide-react";
import { LENS_DEFINITIONS } from "@/lib/lenses";

export default function BattlecardsPage() {
  const { currentOrg } = useAuth();
  const orgId = currentOrg?.id || "";
  const qc = useQueryClient();
  const [selected, setSelected] = useState<string | null>(null);

  const { data: comps, isLoading } = useQuery({
    queryKey: ["competitors", orgId],
    queryFn: () => competitors.list(orgId),
    enabled: !!orgId,
  });

  const { data: analysis, isLoading: loadingAnalysis } = useQuery({
    queryKey: ["competitor-analysis", orgId, selected],
    queryFn: () => ai.getCompetitorAnalysis(orgId, selected!),
    enabled: !!orgId && !!selected,
  });

  const runAnalysis = useMutation({
    mutationFn: (cid: string) => ai.analyzeCompetitor(orgId, cid),
    onSuccess: (_, cid) => {
      qc.invalidateQueries({ queryKey: ["competitor-analysis", orgId, cid] });
      qc.invalidateQueries({ queryKey: ["competitors", orgId] });
      qc.invalidateQueries({ queryKey: ["ai-summary", orgId] });
    },
  });

  if (isLoading) return <Skeleton className="h-64" />;

  return (
    <div className="space-y-6 max-w-6xl">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Battlecards</h1>
        <p className="text-muted-foreground">
          3-lens competitive analysis generated by Claude from your product context
        </p>
      </div>

      {!comps || comps.length === 0 ? (
        <Card>
          <EmptyState
            icon={Shield}
            title="Add competitors to generate battlecards"
            description="Observatory uses Claude to synthesize a battlecard for each tracked competitor — strengths, weaknesses, objection handling, and a three-lens analysis."
            action={{ label: "Add competitors", href: "/competitors" }}
          />
        </Card>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-6">
          {/* Competitor list */}
          <div className="space-y-2">
            {comps.map((c) => {
              const isSel = selected === c.id;
              // @ts-expect-error has_analysis from backend
              const hasA = c.has_analysis;
              return (
                <button
                  key={c.id}
                  onClick={() => setSelected(c.id)}
                  className={`w-full text-left p-3 rounded-lg border transition-all ${
                    isSel
                      ? "border-zinc-900 dark:border-white bg-zinc-50 dark:bg-zinc-900"
                      : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-300"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-medium text-sm">{c.name}</span>
                    {hasA && (
                      <Badge variant="secondary" className="text-[10px]">
                        Analysed
                      </Badge>
                    )}
                  </div>
                  {c.website_url && (
                    <p className="text-xs text-muted-foreground truncate mt-0.5">
                      {c.website_url}
                    </p>
                  )}
                </button>
              );
            })}
          </div>

          {/* Analysis detail */}
          <div>
            {!selected ? (
              <Card>
                <EmptyState
                  icon={Sparkles}
                  title="Select a competitor"
                  description="Pick a competitor from the list to view or generate their battlecard."
                />
              </Card>
            ) : loadingAnalysis ? (
              <Skeleton className="h-96" />
            ) : !analysis ? (
              <Card>
                <CardContent className="pt-6 pb-6 text-center space-y-3">
                  <Sparkles className="h-8 w-8 mx-auto text-muted-foreground" />
                  <div>
                    <p className="font-medium">No battlecard yet</p>
                    <p className="text-sm text-muted-foreground">
                      Generate a Claude-powered analysis using your product + lens context.
                    </p>
                  </div>
                  <Button
                    onClick={() => runAnalysis.mutate(selected)}
                    disabled={runAnalysis.isPending}
                  >
                    {runAnalysis.isPending ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Generating…
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4 mr-2" />
                        Generate battlecard
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>
            ) : (
              <>
                <BattlecardDetail
                  data={analysis.analysis}
                  generatedAt={analysis.generated_at}
                  onRegenerate={() => runAnalysis.mutate(selected)}
                  regenerating={runAnalysis.isPending}
                />
                <GatheredIntelligence orgId={orgId} competitorName={comps?.find((c) => c.id === selected)?.name || ""} />
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function BattlecardDetail({
  data,
  generatedAt,
  onRegenerate,
  regenerating,
}: {
  data: CompetitorAnalysis;
  generatedAt: string;
  onRegenerate: () => void;
  regenerating: boolean;
}) {
  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs text-muted-foreground">
            Generated {new Date(generatedAt).toLocaleString()}
          </p>
        </div>
        <Button size="sm" variant="outline" onClick={onRegenerate} disabled={regenerating}>
          {regenerating ? (
            <Loader2 className="h-3 w-3 mr-1 animate-spin" />
          ) : (
            <Sparkles className="h-3 w-3 mr-1" />
          )}
          Regenerate
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Overview</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm">{data.overview}</p>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <BulletCard title="Strengths" items={data.strengths} />
        <BulletCard title="Weaknesses" items={data.weaknesses} />
        <BulletCard title="Differentiators" items={data.differentiators} />
        <BulletCard title="Recommended actions" items={data.recommended_actions} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Multi-lens analysis</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {Object.entries(data.lens_analysis || data.three_lens_analysis || {}).map(([key, text]) => {
            const def = LENS_DEFINITIONS.find((l) => l.key === key);
            return (
              <LensRow
                key={key}
                icon={def?.icon || Shield}
                label={def?.title || key}
                text={text}
              />
            );
          })}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Objection handling</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.objections.map((o, i) => (
            <div key={i} className="p-3 rounded-lg border text-sm">
              <p className="font-medium">“{o.objection}”</p>
              <p className="text-muted-foreground mt-1">→ {o.response}</p>
            </div>
          ))}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <BulletCard title="Win themes" items={data.win_themes} />
        <BulletCard title="Loss reasons" items={data.loss_reasons} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Pricing posture</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm">{data.pricing_posture}</p>
        </CardContent>
      </Card>
    </div>
  );
}

function BulletCard({ title, items }: { title: string; items: string[] }) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <ul className="space-y-1.5 text-sm">
          {items.map((item, i) => (
            <li key={i} className="flex gap-2">
              <span className="text-muted-foreground">•</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  );
}

function GatheredIntelligence({ orgId, competitorName }: { orgId: string; competitorName: string }) {
  const { data: feeds } = useQuery({
    queryKey: ["intel-feeds", orgId],
    queryFn: () => intel.feeds(orgId),
    enabled: !!orgId,
  });

  const filtered = (feeds || []).filter(
    (f) => f.query?.toLowerCase().includes(competitorName.toLowerCase()) || f.competitor_id
  );

  if (filtered.length === 0) return null;

  const SOURCE_COLORS: Record<string, string> = {
    firecrawl: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
    perplexity: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
    hackernews: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
    reddit: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300",
    academic: "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300",
  };

  return (
    <Card className="mt-4">
      <CardHeader>
        <CardTitle className="text-base">Gathered Intelligence</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {filtered.map((f) => (
          <div key={f.id} className="p-3 rounded-lg border text-sm space-y-1">
            <div className="flex items-center gap-2">
              <Badge variant="secondary" className={`text-[10px] ${SOURCE_COLORS[f.source] || ""}`}>
                {f.source}
              </Badge>
              <span className="text-xs text-muted-foreground">{f.query}</span>
            </div>
            <p className="text-muted-foreground text-xs">{f.content.slice(0, 200)}{f.content.length > 200 ? "..." : ""}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

function LensRow({
  icon: Icon,
  label,
  text,
}: {
  icon: React.ElementType;
  label: string;
  text: string;
}) {
  return (
    <div className="flex gap-3">
      <div className="shrink-0 w-8 h-8 rounded-lg bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center">
        <Icon className="h-4 w-4" />
      </div>
      <div className="flex-1">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          {label}
        </p>
        <p className="text-sm mt-0.5">{text}</p>
      </div>
    </div>
  );
}
